[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.152.2"  # <-- BURAYA SENİN VERSİYONUNU YAZ (Örn: 0.128.0)
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
